# Site settings
title:
email: skylerclayne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Skyler Layne. I'm a software engineering student. I love cats and all things code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://skylerto.github.io" # the base hostname & protocol for your site
twitter_username: skylerto
github_username:  skylerto

# Build settings
markdown: kramdown
pygments: true
